language: r

cache:
  packages: true

addons:
  apt:
    packages:
      # sf
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - libcurl4-openssl-dev

r_packages:
  - pkgdown
  - curl

r_github_packages:
  - yiluheihei/leafletCN

before_install:
  - git config --global user.email "yiluheihei@gmail.com"
  - git config --global user.name "yiluheihei"

script:
  # - travis_wait Rscript -e "pkgdown::build_site()"

after_success:
  # - git add --all *
  # - git commit -m "Update the pkg site" || true
  # - git push -q https://${GITHUB_PAT}@github.com/yiluheihei/ncovmap.git HEAD:master
