---
title: "ncov 2019"
date: "`r format(Sys.time(), '%Y年%m月%d日')`"
output: 
  - github_document
---

```{r set}
knitr::opts_chunk$set(
  fig.path = "man/figures/",
  message = FALSE
)
```

ncov 疫情图，参考[ncovr](https://github.com/pzhaonet/ncovr), 具体使用详情见[vignette](https://yiluheihei.github.io/ncovmap/articles/Introduction.html). 暂放于此，后续可并入[ncovr](https://github.com/pzhaonet/ncovr)

## 数据来源

数据获取通过[DXY-COVID-19-Crawler](https://github.com/BlankerL/DXY-COVID-19-Crawler) 
api 下载，调用`get_ncov()`即可获取。


## 安装

```{r eval=FALSE}
if (!require(remotes)) install.packages("remotes")
if (!require(ncovmap)) remotes::install_github("yiluheihei/ncovmap")
```

```{r load-ncovmap,message=FALSE}
library(ncovmap)
library(leafletCN)
```

## 下载ncov数据

```{r data, message=FALSE}
ncov <- get_ncov2()
ncov
```

## 提取省市或国家数据

```{r subset}
# 中国数据
china <- ncov['china']
china
# 省市数据
hubei <- ncov['湖北省']
hubei
beijing <- ncov['北京市']
beijing
beijing$cities
# 世界数据
world <- ncov['world']
world
```

## 国内总体疫情图

```{r china-map}
plot_china_map(china, legend_position = "bottomleft")
```

## 省份疫情图

湖北省

```{r hubei-map}
plot_province_map(
  hubei, 
  "湖北省", 
  bins = c(0, 100, 200, 500, 1000, 10000)
)
```

北京市

```{r beijing-map}
plot_province_map(
  beijing,
  "北京市", 
  bins = c(0, 10, 50, 100)
)
```

## 世界疫情图

```{r world-map}
plot_world_map(world, legend_position = "bottomleft")
```
